flight_delay_dbt:
  target: dev
  outputs:
    dev:
      type: snowflake
      role: ACCOUNTADMIN
      warehouse: COMPUTE_WH
      database: DBT_FLIGHT_DEMO
      schema: SILVER
      account: ' '
      user: ' '
